model:
  input_dim: 1
  hidden_dims: [32, 16]   # thay vì [64, 32, 32]
  kernel_size: 3

data_loader:
  sequence_length: 8      # thay vì 10
  batch_size: 2           # thay vì 8
  resize_shape: [128, 128]  # thay vì [256, 256]

hyperparameters:
  learning_rate: 0.0001